# Generated by Django 5.2.8 on 2025-12-07 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='À propos de nous', max_length=100)),
                ('about_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('about_author', models.CharField(blank=True, max_length=100)),
                ('about_fonction', models.CharField(blank=True, max_length=150)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('Home', 'Home'), ('About', 'About'), ('Contact', 'Contact'), ('Service', 'Service'), ('Service_Detail', 'Service Detail'), ('Gallery', 'Gallery'), ('Team', 'Team'), ('Pricing', 'Pricing'), ('Blog', 'Blog')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='Classe icône')),
                ('order', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='NOS COLLECTIONS EXCLUSIVES', max_length=100)),
                ('main_title', models.CharField(default='Découvrez nos gammes de bijoux raffinés', max_length=200)),
                ('description', models.TextField(default="Des créations uniques pour chaque occasion, de l'élégance discrète à la pièce statement")),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Pourquoi Nous Choisir', max_length=100)),
                ('main_title', models.CharField(default='Des bijoux qui racontent votre histoire !', max_length=200)),
                ('description', models.TextField(default="Chaque pièce est une œuvre d'art unique, créée avec passion et expertise. De la conception à la réalisation, nous nous engageons pour l'excellence et l'authenticité.")),
                ('phone_label', models.CharField(default='CONSEIL PERSONNALISÉ', max_length=100)),
                ('phone_number', models.CharField(default='+33 1 23 45 67 89', max_length=50)),
                ('phone_display', models.CharField(default='+33 1 23 45 67 89', max_length=50)),
                ('background_image', models.ImageField(blank=True, help_text='Image de fond pour la section', null=True, upload_to='cta/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('popular', 'Popular'), ('enterprise', 'Enterprise')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(default='/month', max_length=50)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('button_text', models.CharField(default='CHOOSE PLAN', max_length=50)),
                ('button_link', models.URLField(default='#')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('air', 'Air Freight'), ('maritime', 'Maritime Freight'), ('ground', 'Ground Freight'), ('home', 'Home Delivery'), ('warehouse', 'Warehouse'), ('support', 'Support 24x7')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('read_more_link', models.URLField(default='#')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SidebarContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('about', 'À propos'), ('popular_posts', 'Articles populaires'), ('gallery', 'Galerie'), ('tags', 'Tags')], max_length=20, verbose_name='Type de contenu')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=1, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Contenu sidebar',
                'verbose_name_plural': 'Contenus sidebar',
                'ordering': ['order', 'content_type'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TP WEB L3 Info', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 234 567890', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Bijoux & Créations', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('logo_white', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('buy_button_text', models.CharField(default='ACHETER MAINTENANT', max_length=50)),
                ('buy_button_url', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('dribbble_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=500, verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10, verbose_name='Statut')),
                ('featured_image', models.ImageField(upload_to='blog/', verbose_name='Image principale')),
                ('thumbnail', models.ImageField(blank=True, upload_to='blog/thumbnails/', verbose_name='Miniature')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description SEO')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('display_order', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.blogcategory', verbose_name='Catégorie')),
                ('related_posts', models.ManyToManyField(blank=True, to='website.blogpost', verbose_name='Articles connexes')),
                ('tags', models.ManyToManyField(blank=True, to='website.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publication_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Collection Or', max_length=100)),
                ('description', models.TextField(help_text='Ex: Élégance intemporelle en or 18 carats', max_length=200)),
                ('image', models.ImageField(help_text='Image de la collection', upload_to='collections/')),
                ('link', models.CharField(blank=True, help_text='Lien vers la page de détail', max_length=200)),
                ('display_order', models.IntegerField(default=1, help_text="Ordre d'affichage")),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.collection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.blogpost', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_source', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.gallerycategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Texte du lien', max_length=100)),
                ('url', models.CharField(help_text='URL ou nom de route Django', max_length=200)),
                ('is_external', models.BooleanField(default=False, help_text='Lien externe?')),
                ('order', models.IntegerField(default=1, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True)),
                ('has_dropdown', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.navigationitem')),
            ],
            options={
                'verbose_name': 'Élément de navigation',
                'verbose_name_plural': 'Éléments de navigation',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.pricingplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('img', models.CharField(help_text="Nom du fichier image (ex: 'icon1.png')", max_length=100)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_service', to='website.about')),
            ],
        ),
    ]
