# Generated by Django 5.2.8 on 2025-12-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Get In Touch', max_length=100)),
                ('main_title', models.CharField(default='Talk or Meet with Us', max_length=200)),
                ('address_title', models.CharField(default='Get Us Here', max_length=100)),
                ('address_line1', models.CharField(default='1355 Market St, Suite 900', max_length=200)),
                ('address_line2', models.CharField(default='San Francisco, CA 94', max_length=200)),
                ('phone_title', models.CharField(default='Call Us', max_length=100)),
                ('phone_number', models.CharField(default='+1 123 456 7890', max_length=50)),
                ('email_title', models.CharField(default='Write Us', max_length=100)),
                ('email_address', models.EmailField(default='info@thisone.com', max_length=254)),
                ('form_title', models.CharField(default='Estimate Project', max_length=100)),
                ('form_heading', models.CharField(default='Let Us Know Here', max_length=200)),
                ('submit_button_text', models.CharField(default='SEND MESSAGE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('message', models.TextField(verbose_name='Message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé')], default='new', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
