# Generated by Django 5.2.8 on 2025-12-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactinfo_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('css_class', models.CharField(help_text="Classe pour le filtrage (ex: 'roadandtruck')", max_length=100, verbose_name='Classe CSS')),
                ('display_order', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie Portfolio',
                'verbose_name_plural': 'Catégories Portfolio',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Our Gallery', max_length=100)),
                ('main_title', models.CharField(default='Seamless logistics, faster deliveries', max_length=200)),
                ('description', models.TextField(default="Whatever item needs to be delivered or shipped, we're capable to do that!")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('video_youtube', 'Vidéo YouTube'), ('video_vimeo', 'Vidéo Vimeo')], default='image', max_length=20, verbose_name='Type')),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnails/', verbose_name='Miniature')),
                ('full_image', models.ImageField(blank=True, null=True, upload_to='portfolio/full/', verbose_name='Image pleine taille')),
                ('video_url', models.URLField(blank=True, verbose_name='URL vidéo')),
                ('video_id', models.CharField(blank=True, max_length=100, verbose_name='ID vidéo')),
                ('display_order', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.portfoliocategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Élément Portfolio',
                'verbose_name_plural': 'Éléments Portfolio',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
