# Generated by Django 5.2.8 on 2025-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_portfoliocategory_portfoliosection_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
