# Generated by Django 5.2.8 on 2025-12-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_portfoliocategory_display_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='read_more_link',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_filename',
            field=models.CharField(blank=True, help_text="Nom du fichier dans static (ex: '1.svg')", max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Image icône'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
