# Generated by Django 5.2.8 on 2025-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_teammember_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Ville, pays')),
                ('quote', models.TextField(verbose_name='Témoignage')),
                ('image', models.ImageField(help_text='Format recommandé : 100x100 pixels', upload_to='testimonials/', verbose_name='Photo du client')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.IntegerField(default=0, help_text='Plus le nombre est petit, plus le témoignage apparaît en premier', verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
