# Generated by Django 5.2.8 on 2025-12-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='quote',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=1, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo_filename',
            field=models.CharField(blank=True, help_text="Nom du fichier dans static (ex: '1.jpg')", max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(help_text='Ex: Los Angeles, USA', max_length=100, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
