# Generated by Django 5.2.8 on 2025-12-10 13:47

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sous-titre')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Image optimisée pour le slider (1920x1080 recommandé)', keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='slider/images/', verbose_name='Image')),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Miniature 60x60 pour la navigation', keep_meta=True, null=True, quality=75, scale=None, size=[60, 60], upload_to='slider/thumbnails/', verbose_name='Miniature')),
                ('video', models.FileField(blank=True, help_text='Vidéo MP4 pour fond (optionnelle)', null=True, upload_to='slider/videos/', verbose_name='Vidéo de fond')),
                ('transition', models.CharField(choices=[('zoomout', 'Zoom Out'), ('fade', 'Fondu'), ('slide', 'Glissement'), ('parallax', 'Parallaxe')], default='zoomout', max_length=50, verbose_name='Transition')),
                ('button_text', models.CharField(default='BOOK NOW', max_length=50, verbose_name='Texte du bouton')),
                ('button_link', models.CharField(default='#', help_text='URL ou #anchor', max_length=500, verbose_name='Lien du bouton')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_duration', models.PositiveIntegerField(default=5, help_text='Durée avant changement automatique', verbose_name="Durée d'affichage (s)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slider',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paramètres du Slider', max_length=100, verbose_name='Nom des paramètres')),
                ('animation_speed', models.PositiveIntegerField(default=2000, help_text='Durée des animations en millisecondes', verbose_name="Vitesse d'animation (ms)")),
                ('autoplay', models.BooleanField(default=True, verbose_name='Lecture automatique')),
                ('autoplay_delay', models.PositiveIntegerField(default=5000, help_text='Délai entre les slides en millisecondes', verbose_name='Délai autoplay (ms)')),
                ('loop', models.BooleanField(default=True, verbose_name='Boucle infinie')),
                ('show_navigation', models.BooleanField(default=True, verbose_name='Afficher la navigation')),
                ('show_bullets', models.BooleanField(default=True, verbose_name='Afficher les indicateurs')),
                ('show_timer', models.BooleanField(default=True, help_text='Barre colorée en bas du slider', verbose_name='Afficher la barre de progression')),
                ('timer_color', models.CharField(default='#D22701', help_text='Couleur hexadécimale (#RRGGBB)', max_length=7, verbose_name='Couleur de la barre de progression')),
                ('mobile_breakpoint', models.PositiveIntegerField(default=768, help_text="Largeur d'écran pour le mode mobile", verbose_name='Point de rupture mobile (px)')),
                ('overlay_opacity', models.FloatField(default=0.5, help_text='0 = transparent, 1 = opaque', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name="Opacité de l'overlay")),
                ('lazy_load', models.BooleanField(default=True, help_text='Charge les images seulement quand nécessaire', verbose_name='Chargement différé')),
                ('preload_images', models.BooleanField(default=True, verbose_name='Préchargement des images')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Paramètres du slider',
                'verbose_name_plural': 'Paramètres du slider',
            },
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Texte')),
                ('link', models.CharField(max_length=500, verbose_name='Lien')),
                ('button_color', models.CharField(default='#D22701', max_length=7, verbose_name='Couleur du bouton')),
                ('vertical_offset', models.IntegerField(default=120, help_text='Position verticale depuis le centre', verbose_name='Décalage vertical')),
                ('animation_delay', models.PositiveIntegerField(default=1000, verbose_name="Délai d'animation (ms)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='website.slider', verbose_name='Slide')),
            ],
            options={
                'verbose_name': 'Appel à action',
                'verbose_name_plural': 'Appels à action',
            },
        ),
    ]
