# Generated by Django 5.2.8 on 2025-12-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_slider_slidersettings_calltoaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(choices=[('excellence', 'Notre Excellence'), ('savoir-faire', 'Notre Savoir-faire'), ('expertise', 'Notre Expertise')], default='excellence', max_length=50, verbose_name='Titre de section')),
                ('main_title', models.CharField(default="Un savoir-faire<br>d'exception", max_length=200, verbose_name='Titre principal')),
                ('description', models.TextField(default="Chaque bijou est le fruit d'un processus créatif rigoureux et d'une expertise transmise de génération en génération.", max_length=500, verbose_name='Description principale')),
                ('image', models.ImageField(help_text='Image pour la section (atelier, artisan, etc.)', upload_to='expertise/', verbose_name='Image principale')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Afficher cette section sur le site', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Section Savoir-faire',
                'verbose_name_plural': 'Sections Savoir-faire',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Sélection des Matériaux, Création sur Mesure, etc.', max_length=100, verbose_name="Titre de l'élément")),
                ('content', models.TextField(help_text="Texte détaillé affiché dans l'accordéon", max_length=1000, verbose_name='Contenu')),
                ('accordion_id', models.CharField(help_text="Identifiant unique pour l'accordéon (ex: collapseOne, collapseTwo)", max_length=50, unique=True, verbose_name='ID Accordéon')),
                ('is_expanded', models.BooleanField(default=False, help_text="Si coché, l'élément sera ouvert au chargement de la page", verbose_name='Déployé par défaut')),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Ordre dans l'accordéon", verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('expertise_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.expertisesection', verbose_name='Section Savoir-faire')),
            ],
            options={
                'verbose_name': 'Élément de savoir-faire',
                'verbose_name_plural': 'Éléments de savoir-faire',
                'ordering': ['display_order', 'title'],
                'unique_together': {('expertise_section', 'accordion_id')},
            },
        ),
    ]
