# Generated by Django 5.2.8 on 2025-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_expertisesection_expertiseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Prénom ou nom complet', max_length=100, verbose_name='Nom')),
                ('position', models.CharField(help_text='Ex: CEO, Director, Manager, etc.', max_length=100, verbose_name='Poste')),
                ('image', models.ImageField(help_text='Photo du membre (format carré recommandé: 400x400px)', upload_to='team/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, help_text='Description courte du membre (optionnel)', max_length=500, verbose_name='Biographie')),
                ('social_media', models.JSONField(blank=True, default=dict, help_text='Format: {"twitter": "url", "linkedin": "url"}', verbose_name='Réseaux sociaux')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text="Afficher ce membre dans l'équipe", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'verbose_name_plural': "Membres d'équipe",
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Our Team', max_length=100, verbose_name='Titre de section')),
                ('main_title', models.CharField(default='Meet our the best crew', max_length=200, verbose_name='Titre principal')),
                ('description', models.TextField(default="Whatever item needs to be delivered or shipped, we're capable to do that!", max_length=500, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Afficher cette section sur le site', verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Position de la section sur la page', verbose_name="Ordre d'affichage")),
                ('background_color', models.CharField(default='#f8f9fa', help_text='Couleur hexadécimale (#RRGGBB)', max_length=7, verbose_name='Couleur de fond')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('members', models.ManyToManyField(blank=True, related_name='team_sections', to='website.teammember', verbose_name="Membres de l'équipe")),
            ],
            options={
                'verbose_name': 'Section Équipe',
                'verbose_name_plural': 'Sections Équipe',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
