# Generated by Django 5.2.8 on 2025-12-10 16:52

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_teammember_teamsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[120, 120], upload_to='services/icons/', verbose_name='Image icône'),
        ),
    ]
