# Generated by Django 5.2.8 on 2025-12-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_service_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='name',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description',
            field=models.CharField(default='All plans include a 30 day trial!', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='period',
            field=models.CharField(default='/month', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('popular', 'Popular'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
        migrations.DeleteModel(
            name='PricingFeature',
        ),
    ]
