# Generated by Django 5.2.8 on 2025-12-10 19:04

import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_pricingplan_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Article de blog', 'verbose_name_plural': 'Articles de blog'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='related_posts',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=django.utils.timezone.now, force_format='WEBP', help_text="Image d'illustration (format recommandé: 800x450px)", keep_meta=True, quality=85, scale=None, size=[800, 450], upload_to='blog/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('inspiration', 'Inspiration'), ('news', 'News'), ('tips', 'Tips & Tricks'), ('company', 'Company News'), ('industry', 'Industry Insights')], default='inspiration', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Contenu complet de l'article"),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text="Court extrait affiché sur la page d'accueil", max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Mettre en avant sur la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
