# Generated by Django 5.2.8 on 2025-12-10 19:20

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_blogpost_options_remove_blogpost_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du client/de la récompense', max_length=200)),
                ('type', models.CharField(choices=[('award', 'Récompense/Prix'), ('client', 'Client'), ('partner', 'Partenaire'), ('certification', 'Certification')], default='client', max_length=50)),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Logo (format recommandé: 200x100px)', keep_meta=True, quality=85, scale=None, size=[200, 100], upload_to='clients/')),
                ('url', models.URLField(blank=True, help_text='Site web du client (optionnel)')),
                ('description', models.TextField(blank=True, help_text='Description courte (optionnel)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.CharField(blank=True, help_text='Année (ex: 2024)', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client/Récompense',
                'verbose_name_plural': 'Clients/Récompenses',
                'ordering': ['order', 'name'],
            },
        ),
    ]
