# Generated by Django 5.2.8 on 2025-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='https://vimeo.com/45830194', help_text='URL de la vidéo (Vimeo, YouTube, etc.)')),
                ('play_icon', models.CharField(default='las la-play', help_text="Classe CSS de l'icône (ex: las la-play, fas fa-play)", max_length=50)),
                ('button_text', models.CharField(blank=True, help_text='Texte à afficher à côté du bouton play (optionnel)', max_length=100)),
                ('background_image', models.ImageField(blank=True, help_text='Image de fond pour la section vidéo', null=True, upload_to='video/')),
                ('background_color', models.CharField(default='#000000', help_text="Couleur de fond (format hex: #000000) si pas d'image", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Vidéo',
                'verbose_name_plural': 'Sections Vidéo',
                'ordering': ['order'],
            },
        ),
    ]
