# Generated by Django 5.2.8 on 2025-12-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_videosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default="LET's Connect", help_text="Titre en haut (ex: LET's Connect)", max_length=100)),
                ('main_title', models.CharField(default='Ready to Ship with Confidence?', help_text='Titre principal', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Effortless Cargo Shipping: Solutions for Businesses of all sizes', help_text='Sous-titre (optionnel)', max_length=300)),
                ('button_text', models.CharField(default='GET A QUOTE', help_text='Texte du bouton', max_length=50)),
                ('button_url', models.CharField(default='#', help_text='URL du bouton', max_length=200)),
                ('background_color', models.CharField(default='#f5f5f5', help_text='Couleur de fond (format hex: #f5f5f5)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Connexion',
                'verbose_name_plural': 'Sections Connexion',
                'ordering': ['display_order'],
            },
        ),
    ]
