# Generated by Django 5.2.8 on 2025-12-10 20:58

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_connectsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la collection', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('gold', 'Collection Or'), ('silver', 'Collection Argent'), ('platinum', 'Collection Platine'), ('wedding', 'Bijoux de Mariage'), ('custom', 'Création Sur Mesure'), ('repair', 'Réparation & Restauration')], max_length=50)),
                ('short_description', models.TextField(help_text='Description courte', max_length=300)),
                ('long_description', models.TextField(help_text='Description détaillée')),
                ('main_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Image principale de la collection', keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='collections/main/')),
                ('featured_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Image pour la liste des collections', keep_meta=True, null=True, quality=85, scale=None, size=[400, 300], upload_to='collections/featured/')),
                ('material', models.CharField(default='Argent 925', help_text='Matériau principal', max_length=100)),
                ('purity', models.CharField(blank=True, help_text='Pureté (ex: 925, 18K)', max_length=50)),
                ('fabrication_process', models.TextField(blank=True, help_text='Description du processus de fabrication')),
                ('delivery_time', models.CharField(blank=True, default='2-5 jours ouvrables', max_length=100)),
                ('custom_order_time', models.CharField(blank=True, default='3-4 semaines', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Mettre en avant sur la page d'accueil")),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection de bijoux',
                'verbose_name_plural': 'Collections de bijoux',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='las la-gem', help_text="Classe d'icône (ex: las la-gem, las la-award)", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.jewelrycollection')),
            ],
            options={
                'verbose_name': 'Caractéristique',
                'verbose_name_plural': 'Caractéristiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CollectionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.jewelrycollection')),
            ],
            options={
                'verbose_name': 'Question/Réponse',
                'verbose_name_plural': 'Questions/Réponses',
                'ordering': ['order'],
            },
        ),
    ]
