# Generated by Django 5.2.8 on 2025-12-10 21:40

import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_jewelrycollection_collectionfeature_collectionfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Air Freight', help_text='Catégorie affichée en haut', max_length=100)),
                ('title', models.CharField(default='For the First Time, Lilly Pulitzer Hosts a Resort Preview', help_text="Titre principal de l'article", max_length=200)),
                ('author', models.CharField(default='John', help_text="Nom de l'auteur", max_length=100)),
                ('published_date', models.DateField(default=django.utils.timezone.now, help_text='Date de publication')),
                ('comment_count', models.PositiveIntegerField(default=3, help_text='Nombre de commentaires')),
                ('view_count', models.PositiveIntegerField(default=5500, help_text='Nombre de vues')),
                ('background_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Image de fond de la bannière (1920x600px recommandé)', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 600], upload_to='blog/banners/')),
                ('article_url', models.CharField(blank=True, default='#', help_text="URL vers l'article complet", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bannière Blog',
                'verbose_name_plural': 'Bannières Blog',
                'ordering': ['-published_date'],
            },
        ),
    ]
