# Generated by Django 5.2.8 on 2025-12-10 22:15

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_blogbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('resume', models.TextField(help_text='Résumé court', max_length=300)),
                ('contenu', models.TextField(help_text='Contenu complet')),
                ('image_principale', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Image principale (800x450px)', keep_meta=True, quality=85, scale=None, size=[800, 450], upload_to='articles/principal/')),
                ('image_galerie_1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[800, 450], upload_to='articles/galerie/')),
                ('image_galerie_2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[800, 450], upload_to='articles/galerie/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_en_vedette', models.BooleanField(default=False)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('url_facebook', models.CharField(blank=True, max_length=200)),
                ('url_twitter', models.CharField(blank=True, max_length=200)),
                ('url_linkedin', models.CharField(blank=True, max_length=200)),
                ('citation', models.TextField(blank=True, help_text='Citation mise en évidence')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='AuteurArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('biographie', models.TextField(blank=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[150, 150], upload_to='auteurs/')),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MotCleArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RechercheBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requete', models.CharField(max_length=200)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_section', models.CharField(choices=[('a_propos', 'À propos'), ('galerie', 'Galerie photo'), ('populaires', 'Articles populaires'), ('recents', 'Articles récents')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Section Sidebar',
                'verbose_name_plural': 'Sections Sidebar',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePopulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clics', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.articleblog')),
            ],
            options={
                'verbose_name': 'Article Populaire',
                'verbose_name_plural': 'Articles Populaires',
                'ordering': ['-clics'],
            },
        ),
        migrations.AddField(
            model_name='articleblog',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.auteurarticle'),
        ),
        migrations.AddField(
            model_name='articleblog',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.categoriearticle'),
        ),
        migrations.CreateModel(
            name='CommentaireArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_approuve', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='website.articleblog')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='website.commentairearticle')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='articleblog',
            name='mots_cles',
            field=models.ManyToManyField(blank=True, to='website.motclearticle'),
        ),
        migrations.CreateModel(
            name='ImageGalerieSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[100, 100], upload_to='blog/sidebar/galerie/')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('section_sidebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_galerie', to='website.sidebarblog')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
