# Generated by Django 5.2.8 on 2025-12-10 22:53

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_articleblog_auteurarticle_categoriearticle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('contenu_principal', models.TextField(help_text="Contenu principal de l'article")),
                ('citation', models.TextField(blank=True, help_text='Citation mise en évidence (blockquote)')),
                ('image_principale', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Image principale (800x450px)', keep_meta=True, quality=85, scale=None, size=[800, 450], upload_to='articles/detail/')),
                ('image_secondaire', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Image secondaire (600x400px)', keep_meta=True, null=True, quality=85, scale=None, size=[600, 400], upload_to='articles/detail/')),
                ('nom_auteur', models.CharField(default='John Doe', max_length=100)),
                ('photo_auteur', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text="Photo de l'auteur (100x100px)", keep_meta=True, null=True, quality=85, scale=None, size=[100, 100], upload_to='auteurs/detail/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_actif', models.BooleanField(default=True)),
                ('lien_facebook', models.CharField(blank=True, max_length=200)),
                ('lien_twitter', models.CharField(blank=True, max_length=200)),
                ('lien_linkedin', models.CharField(blank=True, max_length=200)),
                ('tag_1', models.CharField(blank=True, default='UI/UX', max_length=50)),
                ('tag_2', models.CharField(blank=True, default='Technology', max_length=50)),
                ('tag_3', models.CharField(blank=True, default='Graphics', max_length=50)),
                ('element_liste_1', models.CharField(blank=True, max_length=200)),
                ('element_liste_2', models.CharField(blank=True, max_length=200)),
                ('element_liste_3', models.CharField(blank=True, max_length=200)),
                ('element_liste_4', models.CharField(blank=True, max_length=200)),
                ('element_liste_5', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Article Détaillé',
                'verbose_name_plural': 'Articles Détaillés',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_article', models.CharField(choices=[('populaire', 'Populaire'), ('recent', 'Récent')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[72, 72], upload_to='sidebar/articles/')),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article Sidebar',
                'verbose_name_plural': 'Articles Sidebar',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='CategorieSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('nombre_articles', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie Sidebar',
                'verbose_name_plural': 'Catégories Sidebar',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[100, 100], upload_to='sidebar/galerie/')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Photo Galerie',
                'verbose_name_plural': 'Photos Galerie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[50, 50], upload_to='commentaires/')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_approuve', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='website.articledetail')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='website.commentairedetail')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
