# Generated by Django 5.2.8 on 2025-12-10 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_articledetail_articlesidebar_categoriesidebar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description_courte', models.TextField(help_text='Description courte sous le titre', max_length=300)),
                ('contenu_principal', models.TextField(help_text='Contenu principal')),
                ('citation', models.TextField(blank=True, help_text='Citation (blockquote)')),
                ('sous_titre', models.CharField(blank=True, help_text='Sous-titre après les images', max_length=200)),
                ('texte_sous_titre', models.TextField(blank=True, help_text='Texte sous le sous-titre')),
                ('image_principale', models.ImageField(help_text='Image principale en haut', upload_to='articles/centre/')),
                ('image_gauche', models.ImageField(blank=True, help_text='Image à gauche', null=True, upload_to='articles/centre/')),
                ('nom_auteur', models.CharField(default='Admin', max_length=100)),
                ('photo_auteur', models.ImageField(blank=True, help_text="Photo de l'auteur", null=True, upload_to='auteurs/centre/')),
                ('bio_auteur', models.TextField(blank=True, help_text="Biographie de l'auteur")),
                ('tag_1', models.CharField(blank=True, default='UI/UX', max_length=50)),
                ('tag_2', models.CharField(blank=True, default='Technology', max_length=50)),
                ('tag_3', models.CharField(blank=True, default='Graphics', max_length=50)),
                ('facebook_auteur', models.URLField(blank=True)),
                ('twitter_auteur', models.URLField(blank=True)),
                ('linkedin_auteur', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article Centre',
                'verbose_name_plural': 'Articles Centre',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approuve', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='website.articlecentre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='website.commentairecentre')),
            ],
            options={
                'verbose_name': 'Commentaire Centre',
                'verbose_name_plural': 'Commentaires Centre',
                'ordering': ['-date_creation'],
            },
        ),
    ]
