# Generated by Django 5.2.8 on 2025-12-10 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_articlecentre_commentairecentre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='BIJOUX & CRÉATIONS', max_length=100)),
                ('description', models.TextField(default='Artisans joailliers passionnés créant des bijoux uniques et intemporels depuis 2010.')),
                ('instagram', models.URLField(blank=True, help_text='Lien Instagram')),
                ('facebook', models.URLField(blank=True, help_text='Lien Facebook')),
                ('pinterest', models.URLField(blank=True, help_text='Lien Pinterest')),
                ('tiktok', models.URLField(blank=True, help_text='Lien TikTok')),
                ('adresse', models.TextField(default='12 Rue de la Joaillerie\n75001 Paris, France')),
                ('email', models.EmailField(default='contact@bijoux-creations.fr', max_length=254)),
                ('telephone', models.CharField(default='+33 1 23 45 67 89', max_length=20)),
                ('copyright_texte', models.CharField(default='BIJOUX & CRÉATIONS ©2025. Tous droits réservés', max_length=200)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration Footer',
                'verbose_name_plural': 'Configuration Footer',
            },
        ),
        migrations.CreateModel(
            name='LienFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('boutique', 'Boutique'), ('collections', 'Collections')], max_length=20)),
                ('texte', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='website.footerinfo')),
            ],
            options={
                'verbose_name': 'Lien Footer',
                'verbose_name_plural': 'Liens Footer',
                'ordering': ['type_lien', 'ordre'],
            },
        ),
    ]
