# Generated by Django 5.2.8 on 2025-12-11 04:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_footerinfo_lienfooter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbanner',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogbanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogbanner',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='article_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='background_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_banners/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
