# Generated by Django 5.2.8 on 2025-12-11 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_blogbanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbanner',
            name='page',
            field=models.CharField(choices=[('blog_1', 'blog_1'), ('blog_2', 'blog_2'), ('blog_3', 'blog_3')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
