# Generated by Django 5.2.8 on 2025-12-11 10:53

import django.core.validators
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_blogbanner_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbanner',
            options={'ordering': ['display_order', '-published_date'], 'verbose_name': 'Bannière Blog', 'verbose_name_plural': 'Bannières Blog'},
        ),
        migrations.AddField(
            model_name='blogbanner',
            name='background_color',
            field=models.CharField(default='#1a1a1a', help_text="Couleur hexadécimale (ex: #1a1a1a) si pas d'image", max_length=7, verbose_name='Couleur de fond'),
        ),
        migrations.AddField(
            model_name='blogbanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogbanner',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='blogbanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='article_url',
            field=models.CharField(blank=True, help_text="Lien vers l'article complet (optionnel)", max_length=500, null=True, verbose_name="URL de l'article"),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='author',
            field=models.CharField(default='John', max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Image de fond recommandée: 1920x600px', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 600], upload_to='blog_banners/%Y/%m/%d/', verbose_name='Image de fond'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='category',
            field=models.CharField(help_text='Ex: Transportation, Fashion, Lifestyle, etc.', max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de commentaires'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cocher pour afficher cette bannière', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='page',
            field=models.CharField(choices=[('blog_1', 'Blog_1'), ('blog_2', 'Blog_2'), ('blog_3', 'Blog_3')], default='blog', help_text="Sélectionnez sur quelle page cette bannière s'affichera", max_length=50, verbose_name="Page d'affichage"),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='title',
            field=models.TextField(help_text='Peut contenir des balises <br> pour les sauts de ligne', verbose_name='Titre principal'),
        ),
        migrations.AlterField(
            model_name='blogbanner',
            name='view_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de vues'),
        ),
        migrations.AddIndex(
            model_name='blogbanner',
            index=models.Index(fields=['is_active', 'display_order'], name='website_blo_is_acti_3c1a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogbanner',
            index=models.Index(fields=['page', 'is_active'], name='website_blo_page_0f85b5_idx'),
        ),
    ]
