# Generated by Django 5.2.8 on 2025-12-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_blogbanner_options_blogbanner_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='description',
        ),
    ]
